package currency

import (
	"errors"
	"strings"
)

// Currency contains currency details
type Currency struct {
	AlphaCode   string
	NumericCode string
	Decimal     int
}

// New initialises a new Currency with ISO 4217 alphabetic code and
// returns error if currency is invalid or not found
func New(code string) (*Currency, error) {
	code = strings.ToUpper(code)
	if !IsValid(code) {
		return nil, errors.New("currency: code is not a valid ISO 4217 alphabetic code")
	}

	currency := currencies[code]
	return &currency, nil
}

// IsValid checks if `code` is valid
func IsValid(code string) bool {
	_, ok := currencies[code]
	return ok
}

var (
	// Source: https://www.currency-iso.org/en/home/tables/table-a1.html
	currencies = map[string]Currency{
		"AFN": Currency{"AFN", "971", 2},
		"EUR": Currency{"EUR", "978", 2},
		"ALL": Currency{"ALL", "008", 2},
		"DZD": Currency{"DZD", "012", 2},
		"USD": Currency{"USD", "840", 2},
		"AOA": Currency{"AOA", "973", 2},
		"XCD": Currency{"XCD", "951", 2},
		"ARS": Currency{"ARS", "032", 2},
		"AMD": Currency{"AMD", "051", 2},
		"AWG": Currency{"AWG", "533", 2},
		"AUD": Currency{"AUD", "036", 2},
		"AZN": Currency{"AZN", "944", 2},
		"BSD": Currency{"BSD", "044", 2},
		"BHD": Currency{"BHD", "048", 3},
		"BDT": Currency{"BDT", "050", 2},
		"BBD": Currency{"BBD", "052", 2},
		"BYN": Currency{"BYN", "933", 2},
		"BZD": Currency{"BZD", "084", 2},
		"XOF": Currency{"XOF", "952", 0},
		"BMD": Currency{"BMD", "060", 2},
		"INR": Currency{"INR", "356", 2},
		"BTN": Currency{"BTN", "064", 2},
		"BOB": Currency{"BOB", "068", 2},
		"BOV": Currency{"BOV", "984", 2},
		"BAM": Currency{"BAM", "977", 2},
		"BWP": Currency{"BWP", "072", 2},
		"NOK": Currency{"NOK", "578", 2},
		"BRL": Currency{"BRL", "986", 2},
		"BND": Currency{"BND", "096", 2},
		"BGN": Currency{"BGN", "975", 2},
		"BIF": Currency{"BIF", "108", 0},
		"CVE": Currency{"CVE", "132", 2},
		"KHR": Currency{"KHR", "116", 2},
		"XAF": Currency{"XAF", "950", 0},
		"CAD": Currency{"CAD", "124", 2},
		"KYD": Currency{"KYD", "136", 2},
		"CLP": Currency{"CLP", "152", 0},
		"CLF": Currency{"CLF", "990", 4},
		"CNY": Currency{"CNY", "156", 2},
		"COP": Currency{"COP", "170", 2},
		"COU": Currency{"COU", "970", 2},
		"KMF": Currency{"KMF", "174", 0},
		"CDF": Currency{"CDF", "976", 2},
		"NZD": Currency{"NZD", "554", 2},
		"CRC": Currency{"CRC", "188", 2},
		"HRK": Currency{"HRK", "191", 2},
		"CUP": Currency{"CUP", "192", 2},
		"CUC": Currency{"CUC", "931", 2},
		"ANG": Currency{"ANG", "532", 2},
		"CZK": Currency{"CZK", "203", 2},
		"DKK": Currency{"DKK", "208", 2},
		"DJF": Currency{"DJF", "262", 0},
		"DOP": Currency{"DOP", "214", 2},
		"EGP": Currency{"EGP", "818", 2},
		"SVC": Currency{"SVC", "222", 2},
		"ERN": Currency{"ERN", "232", 2},
		"ETB": Currency{"ETB", "230", 2},
		"FKP": Currency{"FKP", "238", 2},
		"FJD": Currency{"FJD", "242", 2},
		"XPF": Currency{"XPF", "953", 0},
		"GMD": Currency{"GMD", "270", 2},
		"GEL": Currency{"GEL", "981", 2},
		"GHS": Currency{"GHS", "936", 2},
		"GIP": Currency{"GIP", "292", 2},
		"GTQ": Currency{"GTQ", "320", 2},
		"GBP": Currency{"GBP", "826", 2},
		"GNF": Currency{"GNF", "324", 0},
		"GYD": Currency{"GYD", "328", 2},
		"HTG": Currency{"HTG", "332", 2},
		"HNL": Currency{"HNL", "340", 2},
		"HKD": Currency{"HKD", "344", 2},
		"HUF": Currency{"HUF", "348", 2},
		"ISK": Currency{"ISK", "352", 0},
		"IDR": Currency{"IDR", "360", 2},
		"IRR": Currency{"IRR", "364", 2},
		"IQD": Currency{"IQD", "368", 3},
		"ILS": Currency{"ILS", "376", 2},
		"JMD": Currency{"JMD", "388", 2},
		"JPY": Currency{"JPY", "392", 0},
		"JOD": Currency{"JOD", "400", 3},
		"KZT": Currency{"KZT", "398", 2},
		"KES": Currency{"KES", "404", 2},
		"KPW": Currency{"KPW", "408", 2},
		"KRW": Currency{"KRW", "410", 0},
		"KWD": Currency{"KWD", "414", 3},
		"KGS": Currency{"KGS", "417", 2},
		"LAK": Currency{"LAK", "418", 2},
		"LBP": Currency{"LBP", "422", 2},
		"LSL": Currency{"LSL", "426", 2},
		"ZAR": Currency{"ZAR", "710", 2},
		"LRD": Currency{"LRD", "430", 2},
		"LYD": Currency{"LYD", "434", 3},
		"CHF": Currency{"CHF", "756", 2},
		"MOP": Currency{"MOP", "446", 2},
		"MKD": Currency{"MKD", "807", 2},
		"MGA": Currency{"MGA", "969", 2},
		"MWK": Currency{"MWK", "454", 2},
		"MYR": Currency{"MYR", "458", 2},
		"MVR": Currency{"MVR", "462", 2},
		"MRU": Currency{"MRU", "929", 2},
		"MUR": Currency{"MUR", "480", 2},
		"MXN": Currency{"MXN", "484", 2},
		"MXV": Currency{"MXV", "979", 2},
		"MDL": Currency{"MDL", "498", 2},
		"MNT": Currency{"MNT", "496", 2},
		"MAD": Currency{"MAD", "504", 2},
		"MZN": Currency{"MZN", "943", 2},
		"MMK": Currency{"MMK", "104", 2},
		"NAD": Currency{"NAD", "516", 2},
		"NPR": Currency{"NPR", "524", 2},
		"NIO": Currency{"NIO", "558", 2},
		"NGN": Currency{"NGN", "566", 2},
		"OMR": Currency{"OMR", "512", 3},
		"PKR": Currency{"PKR", "586", 2},
		"PAB": Currency{"PAB", "590", 2},
		"PGK": Currency{"PGK", "598", 2},
		"PYG": Currency{"PYG", "600", 0},
		"PEN": Currency{"PEN", "604", 2},
		"PHP": Currency{"PHP", "608", 2},
		"PLN": Currency{"PLN", "985", 2},
		"QAR": Currency{"QAR", "634", 2},
		"RON": Currency{"RON", "946", 2},
		"RUB": Currency{"RUB", "643", 2},
		"RWF": Currency{"RWF", "646", 0},
		"SHP": Currency{"SHP", "654", 2},
		"WST": Currency{"WST", "882", 2},
		"STN": Currency{"STN", "930", 2},
		"SAR": Currency{"SAR", "682", 2},
		"RSD": Currency{"RSD", "941", 2},
		"SCR": Currency{"SCR", "690", 2},
		"SLL": Currency{"SLL", "694", 2},
		"SGD": Currency{"SGD", "702", 2},
		"SBD": Currency{"SBD", "090", 2},
		"SOS": Currency{"SOS", "706", 2},
		"SSP": Currency{"SSP", "728", 2},
		"LKR": Currency{"LKR", "144", 2},
		"SDG": Currency{"SDG", "938", 2},
		"SRD": Currency{"SRD", "968", 2},
		"SZL": Currency{"SZL", "748", 2},
		"SEK": Currency{"SEK", "752", 2},
		"CHE": Currency{"CHE", "947", 2},
		"CHW": Currency{"CHW", "948", 2},
		"SYP": Currency{"SYP", "760", 2},
		"TWD": Currency{"TWD", "901", 2},
		"TJS": Currency{"TJS", "972", 2},
		"TZS": Currency{"TZS", "834", 2},
		"THB": Currency{"THB", "764", 2},
		"TOP": Currency{"TOP", "776", 2},
		"TTD": Currency{"TTD", "780", 2},
		"TND": Currency{"TND", "788", 3},
		"TRY": Currency{"TRY", "949", 2},
		"TMT": Currency{"TMT", "934", 2},
		"UGX": Currency{"UGX", "800", 0},
		"UAH": Currency{"UAH", "980", 2},
		"AED": Currency{"AED", "784", 2},
		"USN": Currency{"USN", "997", 2},
		"UYU": Currency{"UYU", "858", 2},
		"UYI": Currency{"UYI", "940", 0},
		"UYW": Currency{"UYW", "927", 4},
		"UZS": Currency{"UZS", "860", 2},
		"VUV": Currency{"VUV", "548", 0},
		"VES": Currency{"VES", "928", 2},
		"VND": Currency{"VND", "704", 0},
		"YER": Currency{"YER", "886", 2},
		"ZMW": Currency{"ZMW", "967", 2},
		"ZWL": Currency{"ZWL", "932", 2},
	}
)
